"""Sample About icon SVG subpath 2 (head inner) + 3 (body outer) → TypeScript. Requires: pip install svg.path"""
from svg.path import parse_path

# 原 SVG subpath 2：头内圆（相对 subpath 1 末点 512,527.424 → 512,79.424）
HEAD_PATH_D = (
    "M512 79.424"
    "c-105.856 0-192 86.144-192 192"
    "s86.144 192 192 192 192-86.144 192-192-86.144-192-192-192z"
)

# 原 SVG subpath 3：身体外轮廓（相对 subpath 2 末点 512,79.424 → 867.712,1008.576）
BODY_PATH_D = (
    "M867.712 1008.576"
    "h-711.36"
    "A108.416 108.416 0 0 1 48 900.288"
    "C48 712 199.36 560.576 385.344 560.576"
    "h253.312"
    "A337.792 337.792 0 0 1 976 897.92"
    "c0 62.08-48.576 110.656-108.288 110.656z"
)

OUT = (
    r"d:\Baoyu\包宇的cocos\LightPuzzle\assets\Scripts\Games\OpticalPuzzle\Presentation"
    r"\MenuAboutIconSegs.generated.ts"
)

SAMPLE_COUNT = 128


def sample_closed(path_d: str) -> list[tuple[float, float]]:
    path = parse_path(path_d)
    pts = [
        (path.point(i / (SAMPLE_COUNT - 1)).real, path.point(i / (SAMPLE_COUNT - 1)).imag)
        for i in range(SAMPLE_COUNT)
    ]
    if len(pts) > 1:
        x0, y0 = pts[0]
        x1, y1 = pts[-1]
        if abs(x0 - x1) < 0.01 and abs(y0 - y1) < 0.01:
            pts.pop()
    return pts


def normalize_group(groups: list[list[tuple[float, float]]]) -> list[list[tuple[float, float]]]:
    all_pts = [p for g in groups for p in g]
    xs = [p[0] for p in all_pts]
    ys = [p[1] for p in all_pts]
    min_x, max_x = min(xs), max(xs)
    min_y, max_y = min(ys), max(ys)
    cx = (min_x + max_x) * 0.5
    cy = (min_y + max_y) * 0.5
    h = max(max_y - min_y, 1e-6)
    return [[((x - cx) / h, -(y - cy) / h) for x, y in g] for g in groups]


def emit_array(name: str, pts: list[tuple[float, float]]) -> list[str]:
    lines = [f"export const {name}: ReadonlyArray<Readonly<{{ x: number; y: number }}>> = ["]
    for x, y in pts:
        lines.append(f"    {{ x: {x:.8f}, y: {y:.8f} }},")
    lines.append("];")
    return lines


def main() -> None:
    head = sample_closed(HEAD_PATH_D)
    body = sample_closed(BODY_PATH_D)
    norm_head, norm_body = normalize_group([head, body])

    lines = [
        "// AUTO-GENERATED by tools/gen-menu-about-segs.py — do not edit by hand",
        "",
        "/** About icon：SVG subpath 2 头内圆 + subpath 3 身体外轮廓；y 已翻转，按组合 bbox 高度归一化 */",
        *emit_array("MENU_ABOUT_HEAD_SVG_SEGS", norm_head),
        "",
        *emit_array("MENU_ABOUT_BODY_SVG_SEGS", norm_body),
        "",
    ]

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"Wrote head={len(norm_head)} body={len(norm_body)} -> {OUT}")


if __name__ == "__main__":
    main()
