"""Sample SVG outer contour (rounded triangle) → TypeScript polyline. Requires: pip install svg.path"""
from svg.path import parse_path

# 仅外轮廓（右向圆角三角），不含内部镂空 subpath
PATH_D = (
    "M114.035709 861.561237"
    "a114.731104 114.731104 0 0 1-114.032943-114.032943"
    "V114.296382"
    "A113.567502 113.567502 0 0 1 171.05218 15.622979"
    "l548.289006 316.499596"
    "a113.800222 113.800222 0 0 1 0 197.346806"
    "L171.05218 845.968977"
    "a113.567502 113.567502 0 0 1-57.016471 15.59226"
    "z"
)

OUT = (
    r"d:\Baoyu\包宇的cocos\LightPuzzle\assets\Scripts\Games\OpticalPuzzle\Presentation"
    r"\OpticalPuzzleHudArrowSegs.generated.ts"
)

SAMPLE_COUNT = 256


def _area_centroid(pts: list[tuple[float, float]]) -> tuple[float, float]:
    """闭合多边形面积重心（与 svg.path 采样顺序一致）"""
    area2 = 0.0
    cx6 = 0.0
    cy6 = 0.0
    n = len(pts)
    for i in range(n):
        x0, y0 = pts[i]
        x1, y1 = pts[(i + 1) % n]
        cross = x0 * y1 - x1 * y0
        area2 += cross
        cx6 += (x0 + x1) * cross
        cy6 += (y0 + y1) * cross
    if abs(area2) < 1e-9:
        xs = [p[0] for p in pts]
        ys = [p[1] for p in pts]
        return (sum(xs) / n, sum(ys) / n)
    return (cx6 / (3.0 * area2), cy6 / (3.0 * area2))


def main():
    path = parse_path(PATH_D)
    pts = [
        (path.point(i / (SAMPLE_COUNT - 1)).real, path.point(i / (SAMPLE_COUNT - 1)).imag)
        for i in range(SAMPLE_COUNT)
    ]

    # 去掉闭合重复点
    if len(pts) > 1:
        x0, y0 = pts[0]
        x1, y1 = pts[-1]
        if abs(x0 - x1) < 0.01 and abs(y0 - y1) < 0.01:
            pts.pop()

    xs = [p[0] for p in pts]
    ys = [p[1] for p in pts]
    min_x, max_x = min(xs), max(xs)
    min_y, max_y = min(ys), max(ys)
    h = max_y - min_y
    cx, cy = _area_centroid(pts)
    # SVG y 向下 → Cocos y 向上；按高度归一化，原点取面积重心（右向三角 bbox 中心会偏右）
    norm = [((x - cx) / h, -(y - cy) / h) for x, y in pts]

    lines = [
        "// AUTO-GENERATED by tools/gen-hud-arrow-segs.py — do not edit by hand",
        "",
        "/** SVG 外轮廓采样（svg.path）；y 已翻转，按高度归一化，原点为面积重心 */",
        "export const HUD_ARROW_SVG_SEGS: ReadonlyArray<Readonly<{ x: number; y: number }>> = [",
    ]
    for x, y in norm:
        lines.append(f"    {{ x: {x:.8f}, y: {y:.8f} }},")
    lines.append("];")
    lines.append("")

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"Wrote {len(norm)} points, bbox {max_x-min_x:.1f}x{h:.1f}")


if __name__ == "__main__":
    main()
