// AUTO-GENERATED by tools/gen-win-star-segs.js — do not edit by hand
export const WIN_STAR_VIEW_MIN_X = 11.52;
export const WIN_STAR_VIEW_MAX_X = 1013.76;
export const WIN_STAR_VIEW_MIN_Y = 35.84;
export const WIN_STAR_VIEW_MAX_Y = 992;
export const WIN_STAR_VIEW_W = 1002.24;
export const WIN_STAR_VIEW_H = 956.16;
export const WIN_STAR_VIEW_CX = 512.64;
export const WIN_STAR_VIEW_CY = 513.92;

export type WinStarPathSeg =
    | { t: 'M'; x: number; y: number }
    | { t: 'L'; x: number; y: number }
    | { t: 'C'; x1: number; y1: number; x2: number; y2: number; x: number; y: number }
    | { t: 'Z' };

/** 用户 SVG 五角星路径（含圆角贝塞尔与弧段） */
export const WIN_STAR_SEGS: ReadonlyArray<WinStarPathSeg> = [
    { t: 'M', x: 1004.16, y: 393.6 },
    { t: 'C', x1: 994.56, y1: 364.16, x2: 969.6, y2: 343.04, x: 939.52, y: 338.56 },
    { t: 'L', x: 694.4, y: 302.72 },
    { t: 'L', x: 584.96, y: 80.64 },
    { t: 'C', x1: 571.52, y1: 53.12, x2: 544, y2: 35.84, x: 512.64, y: 35.84 },
    { t: 'C', x1: 481.28, y1: 35.84, x2: 454.4, y2: 53.12, x: 440.32, y: 80.64 },
    { t: 'L', x: 330.88, y: 302.72 },
    { t: 'L', x: 85.76, y: 338.56 },
    { t: 'C', x1: 55.04, y1: 343.04, x2: 30.72, y2: 364.16, x: 21.12, y: 393.6 },
    { t: 'C', x1: 11.52, y1: 423.04, x2: 19.2, y2: 454.4, x: 41.6, y: 476.16 },
    { t: 'L', x: 218.88, y: 648.96 },
    { t: 'L', x: 176.64, y: 893.44 },
    { t: 'C', x1: 172.548, y1: 916.841, x2: 179.033, y2: 940.853, x: 194.351, y: 959.012 },
    { t: 'C', x1: 209.668, y1: 977.17, x2: 232.244, y2: 987.61, x: 256, y: 987.52 },
    { t: 'C', x1: 268.8, y1: 987.52, x2: 281.6, y2: 984.32, x: 293.12, y: 977.92 },
    { t: 'L', x: 512.64, y: 862.72 },
    { t: 'L', x: 732.16, y: 977.92 },
    { t: 'C', x1: 759.68, y1: 992, x2: 791.68, y2: 990.08, x: 816.64, y: 972.16 },
    { t: 'C', x1: 841.6, y1: 954.24, x2: 853.76, y2: 924.16, x: 848.64, y: 893.44 },
    { t: 'L', x: 806.4, y: 648.96 },
    { t: 'L', x: 983.68, y: 476.16 },
    { t: 'C', x1: 1005.44, y1: 454.4, x2: 1013.76, y2: 423.04, x: 1004.16, y: 393.6 },
    { t: 'Z' },
];
